name = "api"
compatibility_date = "2024-04-19"
node_compat = true


[durable_objects]
bindings = [
  {name = "SUBSCRIPTION", class_name = "Subscription"}
]

[[r2_buckets]]
binding = "IMAGES" 
bucket_name = "images" 
preview_bucket_name = "images" 

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["Subscription"]

[[ d1_databases ]]
binding = "DB"
database_name = "event-mapping"
database_id = "event-mapping"
migrations_dir = "src/db/migrations"
